### ISSUE TITLE
CNOlist.R: How to assign the basal experimental condition on measurement files

### ISSUE THREAD

**Issue by ptrairatphisan** [saezlab/CellNOptR_packages_archived#1]
It appears that, for the combination of different inputs (activators and/or inhibitors) at different time points, assigning the basal conditions with all combinations of inputs and time points might not always work. Here is an example of a cytochrome P450 model with two stimulators (Cortisol_source and Ligand_2) and one output (CYP3A4_protein) at four different time points (0,10,20,50 minutes). The aim is to have a single logic-ODE model which fits to both full and half concentrations of stimulators. The measurement file is shown below:

<img width="363" alt="assigning_basal_condition" src="https://user-images.githubusercontent.com/20519860/27335262-33913fbe-55cc-11e7-9bd7-1f103e6a23c5.png">

In order to build a CNOlist, all lines with bold red and orange texts should be removed. The orange lines are practically duplicates of the experimental conditions above whereas the red lines which define different concentrations of inputs with readout at time 0 are not necessary. The error message that a user could encounter for improper assignment of the basal experimental condition is as follows:

Error in `[<-`(`*tmp*`, count, , value = 0) : subscript out of bounds

It would be more ideal if either the script would report more useful error or warning messages to notify the users on this problem, or, the developer could write a script to automatically remove the unnecessary lines. In any case, we provide here a quick solution for this problem and it worked well in a few case studies we tested so far.

=====================================================

Note to CellNOptR developers: Using debug(CNOlist) and traceback() returned the following path:
3: makeCNOlist(x, subfield = subfield, verbose = verbose)
2: internal_CNOlist_from_file(data, verbose)
1: CNOlist("CYP3A4_Data_CellNOpt_multipletimepoints_revise3.csv")

The last two steps in the makeCNOlist() function before the script threw an error are as follows:
Browse[4]> n
debug: if (all(zerosCond[which(cues[n, zerosCond] > 0)] == present) && 
    length(which(cues[n, zerosCond] > 0)) != 0) {
    valueSignals[[1]][count, ] <- as.numeric(dataset$dataMatrix[i, 
        dataset$DVcol])
    valueVariance[[1]][count, ] <- as.numeric(variances[i, dataset$DVcol])
    newcues[count, ] <- cues[n, ]
    count = count + 1
}
Browse[4]> n
debug: valueSignals[[1]][count, ] <- as.numeric(dataset$dataMatrix[i, 
    dataset$DVcol])
Browse[4]> n
Error in `[<-`(`*tmp*`, count, , value = 0) : subscript out of bounds

**Comment by gabora** [comment]
This issue happens if your input contains multiple treatment levels instead of binary values. 
In your code you can see 0, 0.5 and 1.0 levels. 

I fixed this issue in the latest commit.
